### ISSUE TITLE
Add "Dayong" to projects

### ISSUE THREAD

**Issue by prLorence** [SurPathHub/docs#1]
**Is your feature request related to a problem? Please describe.**
Dayong is not found in the projects section but there's documentation about it.

**Describe the solution you'd like**
Add Dayong to the projects section using Ugnay Components Web.

![image](https://user-images.githubusercontent.com/78683375/140009645-80ee4788-9c89-4e2e-b928-c2367ced4fa1.png)

**Comment by MatteuSan** [comment]
You wanna work on this? Don't worry about what image to put, you can put a placeholder image that you see fit for the project. We'll get around the official Dayong photo later down the line :)

**Comment by prLorence** [comment]
I can start working on it if that's fine with you. I'll use the description found at Dayong's repo and an image placeholder for the time being.

**Comment by vinzvinci** [comment]
U can start working with this now @prLorence

**Comment by prLorence** [comment]
Thank you!
